name: ardhisasa
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - langchain
      - langchain-openai
      - langchain-community
      - langchain-chroma
      - chromadb
      - openai
      - tiktoken
      - pydantic
      - sqlalchemy
      - requests
